export interface Albumes {
    portada: string[] ;
    nombre: string ;
    tipo: string ;
    dia: string ;
    mes: string ;
    anio: number ;
    canciones: string[] ;
    bandcamp: string;
    bandcamp2: string;
}

export const Discos: Albumes[] =[
    {
        portada: [
            '/src/assets/portadas/GGD.png',
        ],
        nombre: 'Grotesque Genital Dismemberment',
        tipo: 'Demo',
        dia: '',
        mes: 'Abril',
        anio: 1993,
        canciones: [
            'Intro: Unholy ',
            'Grotesque Genital Dismemberment ',
            'Excrement of Infant Skin ',
            'Ulcerous Copulation ',
            'Outro: The Summoning ',
        ],
        bandcamp: '',
        bandcamp2: '',
    },
    {
        portada: ['/src/assets/portadas/SCC.png',],
        nombre: 'Sodomizing Children Corpses',
        tipo: 'Demo',
        dia: '6',
        mes: 'Noviembre',
        anio: 1994,
        canciones: [
            'Intro ',
            'Bizarre Orgasm  ',
            'The Sickest Masturbation (Sex with Animals)  ',
            'Vaginal Disembowelment ',
            'Shrouded in Guiltiness  ',
            'Sodomizing Children Corpses ',
            'Post - Mortal Clitoris Erection ',
            'Divine Molestation ',
        ],
        bandcamp: '',
        bandcamp2: '',
    },
    {
        portada: [
            '/src/assets/portadas/SNK-Pseudo.png',
            '/src/assets/portadas/SNK-Paganus.png',
            ],
        nombre: 'Sinistrous Necromantika / Ascesis al uno Primigenio',
        tipo: 'Compartido',
        dia: '',
        mes: '',
        anio: 1996,
        canciones: [
            'Paganus Doctrina - Ascesis Al Uno Primigenio  ',
            'Pseudostratiffied Epithelium - An Unsatiable Suicidal Stupor   ',
            'Pseudostratiffied Epithelium - Sinistrous Serenades of Perversion   ',
            'Pseudostratiffied Epithelium - Voracious Lascivia  ',
            'Pseudostratiffied Epithelium - Romantic Passions in Rigor Mortis   ',
            'Pseudostratiffied Epithelium - Mandatum Mortuarium  ',
            'Pseudostratiffied Epithelium - Out of the Grace of God ',
            'Pseudostratiffied Epithelium - Cannabic Liquid Fantasies  ',
            'Pseudostratiffied Epithelium - Necromantik Luctus Desecration ',
            'Pseudostratiffied Epithelium - Sombee Bizzarness ',
        ],
        bandcamp: '<iframe style="border: 0; width: 400px; height: 439px;" src="https://bandcamp.com/EmbeddedPlayer/album=582197176/size=large/bgcol=333333/linkcol=e99708/artwork=small/transparent=true/" seamless><a href="https://pseudostratiffiedepithelium.bandcamp.com/album/sinistrous-necromantika">Sinistrous Necromantika by Pseudostratiffied Epithelium</a></iframe>',
        bandcamp2: '',
    },
    {
        portada: ['/src/assets/portadas/ITF.png'],
        nombre: 'Into the Flames',
        tipo: 'Album',
        dia: '',
        mes: '',
        anio: 2004,
        canciones: [
            'The Pupil   ',
            'Red Storm Mass    ',
            'Into the Flames  ',
            'The Overfiend ',
            'Sinister Force     ',
            'Evil Ones   ',
            'The Death of Jesus Christ ',
            'Post Mortal Clitoris Erection   ',
        ],
        bandcamp: '<iframe style="border: 0; width: 400px; height: 406px;" src="https://bandcamp.com/EmbeddedPlayer/album=444771817/size=large/bgcol=333333/linkcol=e99708/artwork=small/transparent=true/" seamless><a href="https://pseudostratiffiedepithelium.bandcamp.com/album/into-the-flames">Into the flames de Pseudostratiffied Epithelium</a></iframe>',
        bandcamp2: '',
    },
    {
        portada: ['/src/assets/portadas/DOLONIA.png'],
        nombre: 'Dolonia',
        tipo: 'Album',
        dia: '3 ',
        mes: 'Mayo ',
        anio: 2007,
        canciones: [
            "Sing, Oh! Goddess, Peleus Son's Wrath    ",
            'Vile and Coward     ',
            'Singular Contest Between Hector and Ayante, the Son of Telamon   ',
            'Desperate Struggle...Fight with Xanthus  ',
            "Antenor's Son ",
            'Dolonia    ',
            "Patroclus' Cadaver ",
            'Sound of My Sorrow, Honour Games to Patroclus    ',
        ],
        bandcamp: '<iframe style="border: 0; width: 400px; height: 406px;" src="https://bandcamp.com/EmbeddedPlayer/album=2263461908/size=large/bgcol=333333/linkcol=e99708/artwork=small/transparent=true/" seamless><a href="https://pseudostratiffiedepithelium.bandcamp.com/album/dolonia">Dolonia de Pseudostratiffied Epithelium</a></iframe>',
        bandcamp2: '',
    },
    {
        portada: ['/src/assets/portadas/EP.png'],
        nombre: 'Psedusotrattified Epithelium',
        tipo: 'Ep',
        dia: '27 ',
        mes: 'Junio ',
        anio: 2015,
        canciones: [
            'Cosmic Energy ',
            'Times of Destruction ',
            'El Toro De Falaris    ',
            'Evil Ones (version regrabada)  ',
        ],
        bandcamp: '<iframe style="border: 0; width: 400px; height: 274px;" src="https://bandcamp.com/EmbeddedPlayer/album=566225372/size=large/bgcol=333333/linkcol=e99708/artwork=small/transparent=true/" seamless><a href="https://pseudostratiffiedepithelium.bandcamp.com/album/pseudostratiffied-epithelium-ep">Pseudostratiffied Epithelium EP by Pseudostratiffied Epithelium</a></iframe>',
        bandcamp2: '',
    },
    {
        portada: [
            '/src/assets/portadas/EP.png',
            '/src/assets/portadas/EP-NCV.png',],
        nombre: 'Pseudostratiffied Epithelium / Necrocannibalistic Vomitorium',
        tipo: 'Compartido',
        dia: '21 ',
        mes: 'Junio ',
        anio: 2019,
        canciones: [
            'Pseudostratiffied Epithelium - Cosmic Energy ',
            'Pseudostratiffied Epithelium - Times of Destruction ',
            'Pseudostratiffied Epithelium - El Toro De Falaris    ',
            'Pseudostratiffied Epithelium - Evil Ones (version regrabada)  ',
            "Necrocannibalistic Vomitorium - Cold Silence      ",
            'Necrocannibalistic Vomitorium - Amphitheater of Death   ',
            'Necrocannibalistic Vomitorium - Math of the War   ',
            'Necrocannibalistic Vomitorium - Skeleton Scale  ',
        ],
        bandcamp: '<iframe style="border: 0; width: 400px; height: 274px;" src="https://bandcamp.com/EmbeddedPlayer/album=566225372/size=large/bgcol=333333/linkcol=e99708/artwork=small/transparent=true/" seamless><a href="https://pseudostratiffiedepithelium.bandcamp.com/album/pseudostratiffied-epithelium-ep">Pseudostratiffied Epithelium EP by Pseudostratiffied Epithelium</a></iframe>',
        bandcamp2: '<iframe style="border: 0; width: 400px; height: 274px;" src="https://bandcamp.com/EmbeddedPlayer/album=3920025224/size=large/bgcol=333333/linkcol=e99708/artwork=small/transparent=true/" seamless><a href="https://necrocannibalisticvomitorium.bandcamp.com/album/split-with-pseudostratiffied-epithelium">Split with Pseudostratiffied Epithelium de Necrocannibalistic Vomitorium</a></iframe>',
    },
    {
        portada: ['/src/assets/portadas/GTA.png'],
        nombre: 'Grave of the Aborted',
        tipo: 'Album',
        dia: '8 ',
        mes: 'Diciembre ',
        anio: 2019,
        canciones: [
            'Restless Death     ',
            'Painful Reflections      ',
            'Book of Decadency    ',
            'Myth of Sisyphus ',
            'Think of Sacrifice ',
            'Who Would You Kill    ',
            'Bestial Rites of Sodomy (version regrabada)',
            'Out of the Grace of God (version regrabada)',
        ],
        bandcamp: '',
        bandcamp2: '',
    },
]